import Constant from "@/utils/Constant.jsx";
import * as clinicalApis from "@/api/system/clinical/index.js";

// SaaS临床页面配置(由业务表字段规范生成)
export const ClinicalConfigs = {

  subject: {
    key: 'subject',
    title: '研究对象',
    module: 'patient_queue',
    subjectBased: false,
    api: {Page: clinicalApis.SubjectPage, SaveOrEdit: clinicalApis.SubjectSaveOrEdit, Del: clinicalApis.SubjectDel},
    search: [{name: 'name', label: '患儿姓名', type: 'input'}, {name: 'subjectNo', label: '研究编号', type: 'input'}],
    columns: ['subjectNo', 'name', 'gender', 'diagnosisGroup', 'birthDate', 'phone', 'centerCode'],
    fields: [
      {name: 'subjectNo', label: '研究编号', type: 'input', required: true},
      {name: 'centerCode', label: '中心编号', type: 'input', required: true},
      {name: 'name', label: '患儿姓名', type: 'input', required: true},
      {name: 'phone', label: '联系电话', type: 'input'},
      {name: 'diagnosisGroup', label: '诊断组', type: 'select', options: [{label: 'PS', value: 1}, {label: 'PA_IVS', value: 2}]},
      {name: 'gender', label: '性别', type: 'select', options: Constant.GenderOptions},
      {name: 'gravidity', label: '孕次G', type: 'number'},
      {name: 'parity', label: '产次P', type: 'number'},
      {name: 'deliveryMode', label: '生产方式', type: 'select', options: Constant.ProductModeOptions},
      {name: 'gestationalWeeks', label: '胎龄周', type: 'number'},
      {name: 'gestationalDays', label: '胎龄天', type: 'number'},
      {name: 'prematureFlag', label: '早产标志', type: 'bool'},
      {name: 'birthDate', label: '出生日期', type: 'date'},
      {name: 'birthWeight', label: '出生体重', type: 'number'},
      {name: 'apgar1min', label: 'Apgar 1分钟', type: 'number'},
      {name: 'apgar5min', label: 'Apgar 5分钟', type: 'number'},
      {name: 'prenatalDiagnosis', label: '产前诊断', type: 'bool'},
      {name: 'fetalIntervention', label: '胎儿干预', type: 'bool'},
      {name: 'nonCardiacMalformationFlag', label: '非心脏畸形标志', type: 'bool'},
      {name: 'nonCardiacMalformationType', label: '非心脏畸形类型', type: 'textarea'},
      {name: 'combinedCardiacDefect', label: '合并心脏畸形', type: 'textarea'},
      {name: 'remark', label: '备注', type: 'textarea'},
    ],
  },
  preIntervention: {
    key: 'preIntervention',
    title: '介入前状态',
    module: 'pre_intervention',
    subjectBased: true,
    api: {Page: clinicalApis.PreInterventionPage, SaveOrEdit: clinicalApis.PreInterventionSaveOrEdit, Del: clinicalApis.PreInterventionDel},
    search: [{name: 'subjectId', label: '研究对象', type: 'subject'}],
    columns: ['recordNo', 'assessTime', 'restSpo2', 'heartRate', 'systolic', 'diastolic'],
    fields: [
      {name: 'recordNo', label: '基线记录编号', type: 'input', required: true},
      {name: 'pbpvId', label: '关联PBPV操作', type: 'input'},
      {name: 'assessTime', label: '评估时间', type: 'datetime'},
      {name: 'restSpo2', label: '静息血氧', type: 'number'},
      {name: 'oxygenWay', label: '吸氧方式', type: 'input'},
      {name: 'fio2', label: '吸入氧浓度', type: 'number'},
      {name: 'cyanosis', label: '发绀', type: 'bool'},
      {name: 'heartRate', label: '心率', type: 'number'},
      {name: 'systolic', label: '收缩压', type: 'number'},
      {name: 'diastolic', label: '舒张压', type: 'number'},
      {name: 'respiratoryRate', label: '呼吸频率', type: 'number'},
      {name: 'pge1Used', label: 'PGE1使用', type: 'bool'},
      {name: 'ventilatorUsed', label: '机械通气', type: 'bool'},
      {name: 'vasoactiveAgent', label: '血管活性药', type: 'input'},
      {name: 'feedingStarted', label: '是否开奶', type: 'bool'},
      {name: 'lactate', label: '乳酸', type: 'number'},
      {name: 'hemoglobin', label: '血红蛋白', type: 'number'},
      {name: 'hematocrit', label: '血细胞比容', type: 'number'},
      {name: 'wbc', label: '白细胞', type: 'number'},
      {name: 'plt', label: '血小板', type: 'number'},
      {name: 'creatinine', label: '肌酐', type: 'number'},
      {name: 'bun', label: '尿素氮', type: 'number'},
      {name: 'sodium', label: '钠', type: 'number'},
      {name: 'potassium', label: '钾', type: 'number'},
      {name: 'alt', label: 'ALT', type: 'number'},
      {name: 'totalBilirubin', label: '总胆红素', type: 'number'},
      {name: 'albumin', label: '白蛋白', type: 'number'},
      {name: 'inr', label: 'INR', type: 'number'},
      {name: 'ntProbnp', label: 'NT-proBNP', type: 'number'},
      {name: 'troponin', label: '肌钙蛋白', type: 'number'},
      {name: 'remark', label: '临床状态备注', type: 'textarea'},
    ],
  },
  pbpv: {
    key: 'pbpv',
    title: 'PBPV操作',
    module: 'pbpv',
    subjectBased: true,
    api: {Page: clinicalApis.PbpvPage, SaveOrEdit: clinicalApis.PbpvSaveOrEdit, Del: clinicalApis.PbpvDel},
    search: [{name: 'recordNo', label: '操作记录编号', type: 'input'}, {name: 'subjectId', label: '研究对象', type: 'subject'}],
    columns: ['recordNo', 'procedureTime', 'weight', 'balloonSize', 'preRvsp', 'postRvsp', 'postPeakGradient'],
    fields: [
      {name: 'recordNo', label: '操作记录编号', type: 'input', required: true},
      {name: 'hospitalizationId', label: '关联住院事件', type: 'input'},
      {name: 'procedureTime', label: 'PBPV日期时间', type: 'datetime', required: true},
      {name: 'procedureDayAge', label: 'PBPV日龄', type: 'number'},
      {name: 'weight', label: '体重', type: 'number'},
      {name: 'height', label: '身长', type: 'number'},
      {name: 'catheterAnnulus', label: '导管测量瓣环', type: 'number'},
      {name: 'balloonSize', label: '球囊大小', type: 'input'},
      {name: 'balloonInflationCount', label: '球囊扩张次数', type: 'number'},
      {name: 'preRvsp', label: '术前RV收缩压', type: 'number'},
      {name: 'prePasp', label: '术前肺动脉收缩压', type: 'number'},
      {name: 'preSystemicPressure', label: '术前体循环压力', type: 'number'},
      {name: 'postRvsp', label: '术后RV收缩压', type: 'number'},
      {name: 'postPasp', label: '术后肺动脉收缩压', type: 'number'},
      {name: 'postAorticPressure', label: '术后降主动脉压力', type: 'number'},
      {name: 'postPeakGradient', label: '术后峰峰压差', type: 'number'},
      {name: 'fluoroTime', label: 'X光暴露时长', type: 'number'},
      {name: 'anesthesiaTime', label: '麻醉时长', type: 'number'},
      {name: 'remark', label: '操作备注', type: 'textarea'},
    ],
  },
  echo: {
    key: 'echo',
    title: '超声检查',
    module: 'echo',
    subjectBased: true,
    api: {Page: clinicalApis.EchoPage, SaveOrEdit: clinicalApis.EchoSaveOrEdit, Del: clinicalApis.EchoDel},
    search: [{name: 'recordNo', label: '超声记录编号', type: 'input'}, {name: 'subjectId', label: '研究对象', type: 'subject'}],
    columns: ['recordNo', 'examTime', 'lvef', 'lvfs', 'tapse', 'trSeverity'],
    fields: [
      {name: 'recordNo', label: '超声记录编号', type: 'input', required: true},
      {name: 'outpatientNo', label: '门诊编号', type: 'input'},
      {name: 'examTime', label: '检查日期时间', type: 'datetime', required: true},
      {name: 'lvedd', label: '左室舒张末期内径', type: 'number'},
      {name: 'lvesd', label: '左室收缩末期内径', type: 'number'},
      {name: 'lvpwd', label: '左室后壁舒张期厚度', type: 'number'},
      {name: 'lvpws', label: '左室后壁收缩期厚度', type: 'number'},
      {name: 'aorticDiameter', label: '主动脉内径', type: 'number'},
      {name: 'laDiameter', label: '左房内径', type: 'number'},
      {name: 'lvef', label: '左室射血分数', type: 'number'},
      {name: 'lvfs', label: '左室缩短率', type: 'number'},
      {name: 'rvEda', label: 'RV-EDA', type: 'number'},
      {name: 'rvEsa', label: 'RV-ESA', type: 'number'},
      {name: 'rvFac', label: 'RV-FAC', type: 'number'},
      {name: 'lvLongDiameter', label: '左室长径', type: 'number'},
      {name: 'lvTransDiameter', label: '左室横径', type: 'number'},
      {name: 'rvLongDiameter', label: '右室长径', type: 'number'},
      {name: 'rvTransDiameter', label: '右室横径', type: 'number'},
      {name: 'tapse', label: 'TAPSE', type: 'number'},
      {name: 'tricuspidDesc', label: '三尖瓣', type: 'input'},
      {name: 'mitralDesc', label: '二尖瓣', type: 'input'},
      {name: 'tvE', label: 'TV-E', type: 'number'},
      {name: 'tvA', label: 'TV-A', type: 'number'},
      {name: 'trSeverity', label: '三尖瓣反流程度', type: 'select', options: [{label: '无', value: 1}, {label: '轻度', value: 2}, {label: '中度', value: 3}, {label: '重度', value: 4}]},
      {name: 'trVelocity', label: 'TR流速', type: 'number'},
      {name: 'trJetWidth', label: '反流束宽', type: 'number'},
      {name: 'tdiRvS', label: 'TDI-RV-S\'', type: 'number'},
      {name: 'tdiRvE', label: 'TDI-RV-E\'', type: 'number'},
      {name: 'tdiRvA', label: 'TDI-RV-A\'', type: 'number'},
      {name: 'eOverEPrime', label: 'E/E\'', type: 'number'},
      {name: 'rvTeiA', label: 'RV-Tei-a', type: 'number'},
      {name: 'rvTeiB', label: 'RV-Tei-b', type: 'number'},
      {name: 'teiIndex', label: 'Tei指数', type: 'number'},
      {name: 'tid', label: 'TID', type: 'number'},
      {name: 'ccd', label: 'CCD', type: 'number'},
      {name: 'tidCcdRatio', label: 'TID/CCD', type: 'number'},
      {name: 'paAnnulus', label: '肺动脉瓣环', type: 'number'},
      {name: 'mpaDiameter', label: '总干内径', type: 'number'},
      {name: 'lpaDiameter', label: '左肺动脉内径', type: 'number'},
      {name: 'rpaDiameter', label: '右肺动脉内径', type: 'number'},
      {name: 'mpaVelocity', label: 'MPA流速', type: 'number'},
      {name: 'rvotVelocity', label: 'RVOT流速', type: 'number'},
      {name: 'prSeverity', label: '肺动脉瓣反流程度', type: 'select', options: [{label: '无', value: 1}, {label: '轻度', value: 2}, {label: '中度', value: 3}, {label: '重度', value: 4}]},
      {name: 'piValue', label: 'PI', type: 'number'},
      {name: 'asdPfoType', label: 'ASD/PFO类型', type: 'select', options: [{label: '无', value: 1}, {label: 'PFO', value: 2}, {label: 'ASD', value: 3}, {label: 'ASD封堵术后', value: 4}]},
      {name: 'asdPfoSize', label: 'ASD/PFO大小', type: 'number'},
      {name: 'shuntDirection', label: '分流方向', type: 'select', options: [{label: '左向右', value: 1}, {label: '双向', value: 2}, {label: '右向左', value: 3}]},
      {name: 'pdaFlag', label: 'PDA', type: 'bool'},
      {name: 'pdaSize', label: 'PDA大小', type: 'number'},
      {name: 'pdaVelocity', label: 'PDA流速', type: 'number'},
      {name: 'remark', label: '备注', type: 'textarea'},
    ],
  },
  cmr: {
    key: 'cmr',
    title: 'CMR检查',
    module: 'cmr',
    subjectBased: true,
    api: {Page: clinicalApis.CmrPage, SaveOrEdit: clinicalApis.CmrSaveOrEdit, Del: clinicalApis.CmrDel},
    search: [{name: 'recordNo', label: 'CMR记录编号', type: 'input'}, {name: 'subjectId', label: '研究对象', type: 'subject'}],
    columns: ['recordNo', 'examDate', 'rvedv', 'rvesv', 'rvef', 'rvEcv'],
    fields: [
      {name: 'recordNo', label: 'CMR记录编号', type: 'input', required: true},
      {name: 'outpatientNo', label: '门诊号', type: 'input'},
      {name: 'examDate', label: '检查日期', type: 'date', required: true},
      {name: 'rvT1', label: '右心室T1', type: 'number'},
      {name: 'rvT1Post', label: '右心室T1\'', type: 'number'},
      {name: 'lvT1', label: '左心室T1', type: 'number'},
      {name: 'lvT1Post', label: '左心室T1\'', type: 'number'},
      {name: 'bloodT1', label: '血池T1', type: 'number'},
      {name: 'bloodT1Post', label: '血池T1\'', type: 'number'},
      {name: 'hct', label: 'HCT', type: 'number'},
      {name: 'rvEcv', label: '右心室ECV', type: 'number'},
      {name: 'lvEcv', label: '左心室ECV', type: 'number'},
      {name: 'rvedv', label: 'RVEDV', type: 'number'},
      {name: 'rvesv', label: 'RVESV', type: 'number'},
      {name: 'rvef', label: 'RVEF', type: 'number'},
      {name: 'rvThickness', label: '右心室厚度', type: 'number'},
      {name: 'paPulseFlow', label: '肺动脉瓣脉搏流量', type: 'number'},
      {name: 'paMaxVelocity', label: '肺动脉过瓣最大流速', type: 'number'},
      {name: 'tvPulseFlow', label: '三尖瓣脉搏流量', type: 'number'},
      {name: 'tvMaxVelocity', label: '三尖瓣过瓣最大流速', type: 'number'},
      {name: 'trFraction', label: '三尖瓣反流分数', type: 'number'},
    ],
  },
  drug: {
    key: 'drug',
    title: '药物暴露',
    module: 'drug',
    subjectBased: true,
    api: {Page: clinicalApis.DrugPage, SaveOrEdit: clinicalApis.DrugSaveOrEdit, Del: clinicalApis.DrugDel},
    search: [{name: 'drugName', label: '药物名称', type: 'input'}, {name: 'subjectId', label: '研究对象', type: 'subject'}],
    columns: ['recordNo', 'drugName', 'dose', 'doseUnit', 'startTime', 'stopTime'],
    fields: [
      {name: 'recordNo', label: '用药记录编号', type: 'input', required: true},
      {name: 'hospitalizationId', label: '关联住院事件', type: 'input'},
      {name: 'drugName', label: '药物标准名称', type: 'input', required: true},
      {name: 'sourceDrugName', label: '源药物名称', type: 'input'},
      {name: 'startTime', label: '开始时间', type: 'datetime'},
      {name: 'stopTime', label: '停止时间', type: 'datetime'},
      {name: 'dose', label: '剂量', type: 'number'},
      {name: 'doseUnit', label: '剂量单位', type: 'input'},
      {name: 'frequency', label: '给药频次', type: 'input'},
      {name: 'route', label: '给药途径', type: 'input'},
      {name: 'remark', label: '备注', type: 'textarea'},
    ],
  },
  hospitalization: {
    key: 'hospitalization',
    title: '住院过程',
    module: 'hospitalization',
    subjectBased: true,
    api: {Page: clinicalApis.HospitalizationPage, SaveOrEdit: clinicalApis.HospitalizationSaveOrEdit, Del: clinicalApis.HospitalizationDel},
    search: [{name: 'recordNo', label: '住院编号', type: 'input'}, {name: 'subjectId', label: '研究对象', type: 'subject'}],
    columns: ['recordNo', 'admissionDate', 'dischargeDate', 'dischargeStatus', 'sourceVentHours'],
    fields: [
      {name: 'recordNo', label: '住院编号', type: 'input', required: true},
      {name: 'admissionDate', label: '入院日期', type: 'date', required: true},
      {name: 'dischargeDate', label: '出院日期', type: 'date'},
      {name: 'icuInTime', label: 'ICU入科日期', type: 'datetime'},
      {name: 'icuOutTime', label: 'ICU出科日期', type: 'datetime'},
      {name: 'ventilatorStart', label: '机械通气开始时间', type: 'datetime'},
      {name: 'ventilatorEnd', label: '机械通气结束时间', type: 'datetime'},
      {name: 'sourceVentHours', label: '源机械通气小时数', type: 'number'},
      {name: 'dischargeStatus', label: '出院状态', type: 'input'},
      {name: 'circulationPath', label: '出院循环路径', type: 'input'},
      {name: 'remark', label: '住院备注', type: 'textarea'},
    ],
  },
  nursing: {
    key: 'nursing',
    title: '术后护理',
    module: 'nursing',
    subjectBased: true,
    api: {Page: clinicalApis.NursingPage, SaveOrEdit: clinicalApis.NursingSaveOrEdit, Del: clinicalApis.NursingDel},
    search: [{name: 'category', label: '记录类别', type: 'select', options: [{label: '体温', value: '体温'}, {label: '心率', value: '心率'}, {label: '呼吸频率', value: '呼吸频率'}, {label: '血压', value: '血压'}, {label: '大便次数', value: '大便次数'}]}, {name: 'subjectId', label: '研究对象', type: 'subject'}],
    columns: ['recordNo', 'category', 'rawValue', 'value1', 'value2', 'recordTime', 'parseStatus'],
    fields: [
      {name: 'recordNo', label: '护理记录编号', type: 'input', required: true},
      {name: 'hospitalizationId', label: '关联住院编号', type: 'input'},
      {name: 'pbpvId', label: '关联PBPV操作', type: 'input'},
      {name: 'category', label: '记录类别', type: 'select', required: true, options: [{label: '体温', value: '体温'}, {label: '心率', value: '心率'}, {label: '呼吸频率', value: '呼吸频率'}, {label: '血压', value: '血压'}, {label: '大便次数', value: '大便次数'}, {label: '其他', value: '其他'}]},
      {name: 'rawValue', label: '原始记录值', type: 'input', required: true},
      {name: 'unit', label: '记录单位', type: 'input'},
      {name: 'recordTime', label: '记录时间', type: 'datetime'},
      {name: 'value1', label: '数值1', type: 'number'},
      {name: 'value2', label: '数值2', type: 'number'},
      {name: 'textValue', label: '文本值', type: 'textarea'},
      {name: 'parseStatus', label: '解析状态', type: 'select', required: true, options: [{label: '已解析', value: 1}, {label: '部分解析', value: 2}, {label: '保留原文', value: 3}]},
      {name: 'remark', label: '备注', type: 'textarea'},
    ],
  },
  followUp: {
    key: 'followUp',
    title: '随访任务',
    module: 'follow_up',
    subjectBased: true,
    api: {Page: clinicalApis.FollowUpPage, SaveOrEdit: clinicalApis.FollowUpSaveOrEdit, Del: clinicalApis.FollowUpDel},
    search: [{name: 'status', label: '状态', type: 'select', options: [{label: '待完成', value: 1}, {label: '已完成', value: 2}, {label: '逾期', value: 3}, {label: '取消', value: 4}]}, {name: 'subjectId', label: '研究对象', type: 'subject'}],
    columns: ['followupType', 'planDate', 'remindDate', 'ownerId', 'status', 'finishDate'],
    fields: [
      {name: 'followupType', label: '随访类型', type: 'select', required: true, options: [{label: '超声', value: 1}, {label: 'CMR', value: 2}, {label: '门诊', value: 3}, {label: '其他', value: 4}]},
      {name: 'planDate', label: '计划日期', type: 'date', required: true},
      {name: 'remindDate', label: '提醒日期', type: 'date'},
      {name: 'ownerId', label: '负责人', type: 'select', required: true, optionsApi: 'userList'},
      {name: 'status', label: '状态', type: 'select', required: true, options: [{label: '待完成', value: 1}, {label: '已完成', value: 2}, {label: '逾期', value: 3}, {label: '取消', value: 4}]},
      {name: 'finishDate', label: '完成日期', type: 'date'},
      {name: 'relatedExamType', label: '关联检查类型', type: 'select', options: [{label: '超声', value: 1}, {label: 'CMR', value: 2}]},
      {name: 'relatedExamId', label: '关联检查记录', type: 'input'},
      {name: 'cancelReason', label: '取消原因', type: 'input'},
      {name: 'remark', label: '备注', type: 'textarea'},
    ],
  },
};
